apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.controller.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app1.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app2.namespace }}
