apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.controller.name }}
  namespace: {{ .Values.controller.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.controller.name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
