apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-ingress-nginx-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ingress-nginx-controller
subjects:
  - kind: ServiceAccount
    name: sa-ingress-nginx-controller
    namespace: {{ .Values.controller.namespace }}
