# Définition d'un Secret pour stocker des informations sensibles encodées en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  user: YWRtaW4=          # 'admin' encodé en base64
  password: MWYyZDFlMmU2N2Rm  # '1f2d1e2e67df' encodé en base64

# Pod 1 : Injection des secrets sous forme de variables d'environnement et affichage dans les logs
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-container-1
spec:
  containers:
    - name: my-container-1
      image: busybox                # image légère avec commandes Unix (cat, printenv)
      command: [ "sh", "-c" ]
      args:
        - echo "Secrets en variables d'environnement :" && echo "USER=$USER" && echo "PASSWORD=$PASSWORD"
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password

# Pod 2 : Montage du Secret en volume et affichage du contenu des fichiers dans les logs
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-container-2
spec:
  containers:
    - name: my-container-2
      image: busybox
      command: [ "sh", "-c" ]
      args:
        - echo "Secrets montés en tant que fichiers :" && cat /etc/secret/user && cat /etc/secret/password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
