apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc
spec:
  replicas: 2
  template:
    # definition POD
    metadata:
      name: app-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
